version: 1
disable_existing_loggers: true

root:
  handlers: [root]
  level: DEBUG

formatters:
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  root:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
    filters: []
    stream: ext://sys.stdout
